exports.tap = require('./modules/tap')
exports.pan = require('./modules/pan')
exports.pinch = require('./modules/pinch')
exports.press = require('./modules/press')
exports.rotate = require('./modules/rotate')
exports.swipe = require('./modules/swipe')